{
  "formatVersion": "1.1",
  "component": {
    "group": "robaertschi.imguirenderer",
    "module": "imguirenderer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imguirenderer-1.0.0.jar",
          "url": "imguirenderer-1.0.0.jar",
          "size": 9935,
          "sha512": "bcb983e390c880d5a591db912d9b016e43e2e685e1a8cd19706d90910b9f86b32616cbaa6abf6796e2521bfc4b9553882e1c5206216d794648b438320dd93211",
          "sha256": "722231f85cb2d154dc90baceff35870d1f427c4be4501f47cf791ea6c2a44ba3",
          "sha1": "2f40a7df6bdd89cde51e720616fd3f8118a7b2f4",
          "md5": "d53616451bf0008ba62563c7910e171c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.1.25_mapped_official_1.20.1"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.86.10"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.86.10"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.86.10"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.86.10"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "imguirenderer-1.0.0.jar",
          "url": "imguirenderer-1.0.0.jar",
          "size": 9935,
          "sha512": "bcb983e390c880d5a591db912d9b016e43e2e685e1a8cd19706d90910b9f86b32616cbaa6abf6796e2521bfc4b9553882e1c5206216d794648b438320dd93211",
          "sha256": "722231f85cb2d154dc90baceff35870d1f427c4be4501f47cf791ea6c2a44ba3",
          "sha1": "2f40a7df6bdd89cde51e720616fd3f8118a7b2f4",
          "md5": "d53616451bf0008ba62563c7910e171c"
        }
      ]
    }
  ]
}
